remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Rik's GitHub Pages Site
description: trying out GitHub Pages features
